import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import { BASE_URL_API } from '../../utils/Constants';

export const userApi = createApi({
  reducerPath: 'userApi',
  baseQuery: fetchBaseQuery({
    baseUrl: BASE_URL_API,
    prepareHeaders: (headers) => {
      headers.set('Content-Type', 'application/json');
      return headers;
    },
  }),
  endpoints: (builder) => ({
    // Register User Mutation
    registerUser: builder.mutation({
      query: ({ name, email, phone, password }) => ({
        url: 'users/create_user',
        method: 'POST',
        body: { name, email, phone, password },
      }),
    }),

    loginUsers:builder.mutation({
      query:({email,password})=>({
        url:'users/login',
        method:'POST',
        body:{
          email,password
        }

      })
    }),

    // Get All Users Query
    getAllUsers: builder.query({
      query: () => 'users/all',
    }),
  }),
});

// Hooks auto-generated by RTK Query
export const { useRegisterUserMutation, useGetAllUsersQuery,useLoginUsersMutation } = userApi;

// Export the reducer to add to the store
export default userApi.reducer;
